app:
  experian.api:
    url:
    token:
  template.plaintext:
    directory: "/WEB-INF/templates/text/"
    file:
      email: "email.txt"

spring:
  session.store-type: none
  thymeleaf:
    check-template-location: false
    prefix:
    excluded-view-names:
    view-names:
    suffix:
    mode: HTML
    encoding: UTF-8
    cache: false